version: "3.3"

services:
  mysql:
    image: mysql:8.0
    container_name: grace_mysql
    restart: always
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3382:3306
    volumes:
      - ./docker/mysql/conf/:/etc/mysql/conf.d
      - ./var/mysql/data:/var/lib/mysql:cached
      - ./var/mysql/logs:/var/log/mysql:rw
      - ./var/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./var/mysql/common:/app:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  grace:
    image: grace_base
    container_name: grace_web
    restart: always
    environment:
      - TZ=${TZ}
      - GRACE_DOMAIN=${GRACE_DOMAIN}
      - GRACE_APP_ROOT_DIR=${GRACE_APP_ROOT_DIR}
    links:
      - mysql:mysql_host
    volumes:
      - ${GRACE_APP_PATH}:${GRACE_APP_ROOT_DIR}:cached

  nginx:
    image: grace_nginx
    container_name: grace_nginx
    restart: always
    environment:
      - TZ=${TZ}
      - GRACE_DOMAIN=${GRACE_DOMAIN}
      - GRACE_APP_ROOT_DIR=${GRACE_APP_ROOT_DIR}
      - SSL_CRT_GRACE=${SSL_CRT_GRACE}
      - SSL_KEY_GRACE=${SSL_KEY_GRACE}
    ports:
      - 8882:80
      - 445:443
    links:
      - grace:grace_host
    volumes:
      - ${GRACE_APP_PATH}:${GRACE_APP_ROOT_DIR}:cached
      - ./docker/nginx/ssl:/etc/nginx/conf.d/ssl
    command: |-
      /bin/sh -c " \
        envsubst '$$GRACE_DOMAIN $$GRACE_APP_ROOT_DIR $$SSL_CRT_GRACE $$SSL_KEY_GRACE' < /etc/nginx/conf.d/grace.conf.template > /etc/nginx/conf.d/grace.conf && \
        nginx -g 'daemon off;'
      "


