# This is a basic workflow to help you get started with Actions

name: "PHP CodeSniffer"


# Controls when the action will run. 
# on: [ push, pull_request ]

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - "**.php"
      - "aas-coding-ruleset.xml"
      - ".github/workflows/phpcs.yml"
  pull_request:
    paths:
      - "**.php"
      - "aas-coding-ruleset.xml"
      - ".github/workflows/phpcs.yml"

# on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  # pull_request:
  #  paths:
  #    - "**.php"
  #    - "aas-coding-ruleset.xml"
  #    - ".github/workflows/phpcs.yml"


# on:
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

# on: [ push, pull_request ]
# on: [pull_request]
# on: pull_request
# on:
#     pull_request:
#       paths:
#         - "**.php"
#         - "phpcs.xml"
#         - ".github/workflows/phpcs.yml"

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get list of all the modified files
        run: git diff-tree --no-commit-id --name-status -r ${{ github.sha }}

      - name: Get list of all the modified php files
        run: git diff-tree --no-commit-id --name-status -r ${{ github.sha }} | grep .php$

      - name: Get changed files excluding deleted files
        id: changedFiles
        run: |
          echo "::set-output name=all::$(git diff-tree --no-commit-id --name-only -r --diff-filter=ACMRT ${{ github.sha }} | xargs)"
          echo "::set-output name=php::$(git diff-tree --no-commit-id --name-only -r --diff-filter=ACMRT ${{ github.sha }} | grep .php$ | xargs)"

      - name: echo output all
        run: |
          echo ${{ steps.changedFiles.outputs.all }}

      - name: echo output php
        run: |
          echo ${{ steps.changedFiles.outputs.php }}


      if: ${{ steps.changedFiles.outputs.php }}
      - name: here run checking php
        run: |
          echo ${{ steps.changedFiles.outputs.php }}

