# This is a basic workflow to help you get started with Actions

name: "PHP CodeSniffer"


# Controls when the action will run. 
# on: [ push, pull_request ]

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - "**.php"
      - "aas-coding-ruleset.xml"
      - ".github/workflows/phpcs.yml"
  pull_request:
    paths:
      - "**.php"
      - "aas-coding-ruleset.xml"
      - ".github/workflows/phpcs.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get_changed_files:
    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      lastRepoEventChange: ${{ steps.changedFiles.outputs.lastRepoEventChange }}
      allUnfiltered: ${{ steps.changedFiles.outputs.allUnfiltered }}
      phpUnfiltered: ${{ steps.changedFiles.outputs.phpUnfiltered }}
      allFilteredACMRT: ${{ steps.changedFiles.outputs.allFilteredACMRT }}
      phpFilteredACMRT: ${{ steps.changedFiles.outputs.phpFilteredACMRT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get last commit in repo
        id: lastEventHash
        run: |
            if ${{ github.event.pull_request.base.sha != '' }}; then
              echo "::set-output name=lastRepoEventChange::${{ github.event.pull_request.base.sha }}"
            else
              echo "::set-output name=lastRepoEventChange::${{ github.event.before }}"
            fi

      - name: Print last commit in repo
        run: |
          echo Commit ID: ${{ steps.lastEventHash.outputs.lastRepoEventChange }}

    #  - name: Loop commits
    #    run: | 
    #      for commit in $(git rev-list ${{ github.event.before}} ${{ github.event.pull_request.base.sha }}..${{ github.sha}}); do
    #          git checkout $commit
    #          echo "run test"
    #      done

      - name: Generate output for changed files
        id: changedFiles
        run: |
          echo "::set-output name=allUnfiltered::$(git diff-tree --no-commit-id --name-status -r ${{ steps.lastEventHash.outputs.lastRepoEventChange }} ${{ github.sha }} | xargs)"
          echo "::set-output name=phpUnfiltered::$(git diff-tree --no-commit-id --name-status -r ${{ steps.lastEventHash.outputs.lastRepoEventChange }} ${{ github.sha }} | grep .php$ | xargs)"
          echo "::set-output name=allFilteredACMRT::$(git diff-tree --no-commit-id --name-only -r --diff-filter=ACMRT ${{ steps.lastEventHash.outputs.lastRepoEventChange }} ${{ github.sha }} | xargs)"
          echo "::set-output name=phpFilteredACMRT::$(git diff-tree --no-commit-id --name-only -r --diff-filter=ACMRT ${{ steps.lastEventHash.outputs.lastRepoEventChange }} ${{ github.sha }} | grep .php$ | xargs)"


  print_changed_files:
    runs-on: ubuntu-latest

    # require the first job to have ran and run this job in sequence
    needs: get_changed_files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get status list of all the modified files
        if: ${{ needs.get_changed_files.outputs.allUnfiltered }}
        run: |
          echo $(git diff-tree --no-commit-id --name-status -r ${{ needs.get_changed_files.outputs.lastRepoEventChange }} ${{ github.sha }})

      - name: Get list of all the modified files excluding deleted files
        if: ${{ needs.get_changed_files.outputs.allFilteredACMRT }}
        run: |
          git diff-tree --no-commit-id --name-only -r --diff-filter=ACMRT ${{ needs.get_changed_files.outputs.lastRepoEventChange }} ${{ github.sha }}

      - name: Get List of status of all the modified php file
        if: ${{ needs.get_changed_files.outputs.phpUnfiltered }}
        run: |
          git diff-tree --no-commit-id --name-status -r ${{ needs.get_changed_files.outputs.lastRepoEventChange }} ${{ github.sha }} | grep .php$

      - name: Get List of all the modified php files excluding deleted files (Will be validated for coding standard)
        if: ${{ needs.get_changed_files.outputs.phpFilteredACMRT }}
        run: |
          git diff-tree --no-commit-id --name-only -r --diff-filter=ACMRT ${{ needs.get_changed_files.outputs.lastRepoEventChange }} ${{ github.sha }} | grep .php$


  validate_coding_standard:
    runs-on: ubuntu-latest

    # require prev jobs to have ran and run this job in sequence
    needs: [get_changed_files, print_changed_files]

    # only run there are changed files
    if: ${{needs.get_changed_files.outputs.phpFilteredACMRT}}
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - name: Check Coding Standard Violations
        run: |
          php phpcs.phar --standard=aas-coding-ruleset.xml --extensions=php ${{ needs.get_changed_files.outputs.phpFilteredACMRT }}

