# This is a basic workflow to help you get started with Actions

name: "PHP CodeSniffer"


# Controls when the action will run. 
# on: [ push, pull_request ]

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - "**.php"
      - "aas-coding-ruleset.xml"
      - ".github/workflows/phpcs.yml"
  pull_request:
    paths:
      - "**.php"
      - "aas-coding-ruleset.xml"
      - ".github/workflows/phpcs.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get_changed_files:
    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      lastRepoEventChange: ${{ steps.lastEventHash.outputs.lastRepoEventChange }}
      allUnfiltered: ${{ steps.changedFiles.outputs.allUnfiltered }}
      phpUnfiltered: ${{ steps.changedFiles.outputs.phpUnfiltered }}
      allFilteredACMRT: ${{ steps.changedFiles.outputs.allFilteredACMRT }}
      phpFilteredACMRT: ${{ steps.changedFiles.outputs.phpFilteredACMRT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Last Event Hash in Repo
        id: lastEventHash
        run: |
            if ${{ github.event.pull_request.base.sha != '' }}; then
              echo "::set-output name=lastRepoEventChange::${{ github.event.pull_request.base.sha }}"
            else
              echo "::set-output name=lastRepoEventChange::${{ github.event.before }}"
            fi

      - name: Print Event Hashes
        run: |
          echo Last Event Hash in Repo: ${{ steps.lastEventHash.outputs.lastRepoEventChange }}
          echo Latest Event Hash: ${{ github.sha }}

      - name: Generate Output for Changed Files
        id: changedFiles
        run: |
          echo "::set-output name=allUnfiltered::$(git diff-tree --no-commit-id --name-status -r ${{ steps.lastEventHash.outputs.lastRepoEventChange }} ${{ github.sha }} | xargs)"
          echo "::set-output name=phpUnfiltered::$(git diff-tree --no-commit-id --name-status -r ${{ steps.lastEventHash.outputs.lastRepoEventChange }} ${{ github.sha }} | grep .php$ | xargs)"
          echo "::set-output name=allFilteredACMRT::$(git diff-tree --no-commit-id --name-only -r --diff-filter=ACMRT ${{ steps.lastEventHash.outputs.lastRepoEventChange }} ${{ github.sha }} | xargs)"
          echo "::set-output name=phpFilteredACMRT::$(git diff-tree --no-commit-id --name-only -r --diff-filter=ACMRT ${{ steps.lastEventHash.outputs.lastRepoEventChange }} ${{ github.sha }} | grep .php$ | xargs)"


  print_changed_files:
    runs-on: ubuntu-latest

    # require the first job to have ran, then run this job in sequence
    needs: get_changed_files

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Status List of All the Modified Files
        if: ${{ needs.get_changed_files.outputs.allUnfiltered }}
        run: |
          git diff-tree --no-commit-id --name-status -r ${{ needs.get_changed_files.outputs.lastRepoEventChange }} ${{ github.sha }}

      - name: Get List of All the Modified Files Excluding Deleted Files
        if: ${{ needs.get_changed_files.outputs.allFilteredACMRT }}
        run: |
          git diff-tree --no-commit-id --name-only -r --diff-filter=ACMRT ${{ needs.get_changed_files.outputs.lastRepoEventChange }} ${{ github.sha }}

      - name: Get List of Status of All the Modified PHP File
        if: ${{ needs.get_changed_files.outputs.phpUnfiltered }}
        run: |
          git diff-tree --no-commit-id --name-status -r ${{ needs.get_changed_files.outputs.lastRepoEventChange }} ${{ github.sha }} | grep .php$

      - name: Get List of All the Modified PHP Files Excluding Deleted Files (Will be validated for coding standard)
        if: ${{ needs.get_changed_files.outputs.phpFilteredACMRT }}
        run: |
          git diff-tree --no-commit-id --name-only -r --diff-filter=ACMRT ${{ needs.get_changed_files.outputs.lastRepoEventChange }} ${{ github.sha }} | grep .php$


  validate_coding_standard:
    runs-on: ubuntu-latest

    # require prev jobs to have ran, then run this job in sequence
    needs: [get_changed_files, print_changed_files]

    # only run there are changed files
    if: ${{ needs.get_changed_files.outputs.phpFilteredACMRT }}
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - name: Check Coding Standard Violations
        run: |
          php phpcs.phar --standard=aas-coding-ruleset.xml --extensions=php ${{ needs.get_changed_files.outputs.phpFilteredACMRT }}

